# From this line onwards, we're in a new image, which will be the image used in production
FROM alezrik/game_services_umbrella:release

COPY game_services_umbrella.tar.gz ./
RUN tar xfz game_services_umbrella.tar.gz
RUN ls -alF bin/
ENTRYPOINT ["bin/game_services_umbrella"]