apiVersion: v1
kind: Service
metadata:
  name: game-services-umbrella-service
spec:
  ports:
  - port: 8080
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: game-services-umbrella
  type: LoadBalancer