apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  secret_key_base: NHpvczdvbmt1ODlpV2xBZWZSYy9KeXdNalh2QW4rZlNUZ1ZDL1djcjJsN041a1JiNnVmK1VuRTZUaE80UEpycQ==
  db_password: cG9zdGdyZXM=